version: "3"
services:
  nginx:
    build:
      context: ./nginx
    ports:
      - 80:80
    links:
      - viper
  viper:
    container_name: viper
    build:
      context: .
    ports:
      - 3000:3000
